### PR TITLE
updates to remaining report README files

### PR DESCRIPTION
**Pull request by julienye**
This pull request includes updates to two reports not previously reviewed: supplying turnaround and requesting ratio. 

I think it also includes previously-reviewed requesting turnaround and overdues reports.

### CODE REVIEW

**Review by kristenwilson — CHANGES_REQUESTED** [review]
Julie, I'm not sure I'm looking at the right version of this, so apologies if you've done this and I'm just not seeing it. For the definition, it seems like should clarify the difference between the average and median times, as well as the counts (requests under 48, etc.).

**Comment by julienye** [comment]
Kristen, the review request included several files, and I'm not sure which
this comment refers to.  I'll send you links to each of my 'final' drafts
via slack.  hopefully that will make it easier for you to see each file...

**Comment by nassibnassar** [comment]
@kristenwilson @julienye If it helps, you can click on the "Files changed" tab, and then click on a plus sign ( `+` ) on the left to select a line (or select multiple lines) in order to leave a comment on a specific file.

**Comment by julienye** [comment]
oh, wow  - that's good to know, thanks, Nassib!

**Comment by julienye** [comment]
@kristenwilson - there is still a question you haven't responded to, in the supplying_turnaround README.  I also just asked you the same question in Slack.  if you reply, I'll remove it from the README file and you can approve the changes and it will all be ready for NN to merge.  Thanks!

**Review by kristenwilson — COMMENTED** [review]
All look good.

**Pull request merged**
